// Pluggable LLM provider.
// - `demo`   : deterministic, template-based responses, NO network / API key needed.
//              This is the default so the whole app runs out-of-the-box.
// - `openai` : uses the `openai` optional dependency when OPENAI_API_KEY is set.
// - `anthropic`: uses `@anthropic-ai/sdk` optional dependency when ANTHROPIC_API_KEY is set.

import type { LLMProvider } from './types.js'

export class DemoProvider implements LLMProvider {
  name = 'demo'

  async complete(prompt: string, _opts?: { system?: string; json?: boolean }): Promise<string> {
    // Simulate a little latency so the UI streaming feels natural.
    await new Promise((r) => setTimeout(r, 120))
    const lower = prompt.toLowerCase()

    // If the caller wants JSON (e.g. structured analysis), return a stub object.
    if (_opts?.json) {
      return JSON.stringify({
        note: 'demo-mode structured response',
        echo: prompt.slice(0, 80),
        generated_at: new Date().toISOString()
      })
    }

    // Produce a plausible, structured answer derived from the prompt content.
    const topic = extractTopic(prompt)
    return [
      `## ${topic.title}`,
      '',
      topic.body,
      '',
      '### Key points',
      '- Identify the primary audience and their trigger moments.',
      '- Lead with one clear value proposition, not a feature list.',
      '- Distribute across 3 channels weighted by where the audience spends time.',
      '- Measure with one north-star metric and two guardrail metrics.',
      '',
      '> _Generated by DemoProvider (no API key). Set OPENAI_API_KEY / ANTHROPIC_API_KEY for real LLM output._'
    ].join('\n')
  }
}

function extractTopic(prompt: string): { title: string; body: string } {
  const m = prompt.match(/\[TASK\]\s*(.+?)\n/)
  const label = m ? m[1].trim() : 'Analysis'
  const goalMatch = prompt.match(/Goal:\s*(.+)/)
  const goal = goalMatch ? goalMatch[1].trim() : 'the product / campaign'
  return {
    title: label,
    body: `Below is a structured draft for "${goal}". In demo mode this is a template; ` +
      `with a real LLM provider it would be a tailored, data-grounded deliverable.`
  }
}

export function getProvider(): LLMProvider {
  const kind = (process.env.AGENT_LLM || 'demo').toLowerCase()
  if (kind === 'openai') return makeOpenAI()
  if (kind === 'anthropic') return makeAnthropic()
  return new DemoProvider()
}

function makeOpenAI(): LLMProvider {
  const apiKey = process.env.OPENAI_API_KEY
  if (!apiKey) {
    console.warn('[provider] OPENAI_API_KEY not set, falling back to demo')
    return new DemoProvider()
  }
  // Lazy require so the optional dependency is only loaded when actually used.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { default: OpenAI } = require('openai') as typeof import('openai')
  const client = new OpenAI({ apiKey })
  return {
    name: 'openai',
    async complete(prompt: string, opts?: { system?: string; json?: boolean }) {
      const resp = await client.chat.completions.create({
        model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
        messages: [
          ...(opts?.system ? [{ role: 'system' as const, content: opts.system }] : []),
          { role: 'user' as const, content: prompt }
        ],
        response_format: opts?.json ? { type: 'json_object' } : undefined
      })
      return resp.choices[0]?.message?.content ?? ''
    }
  }
}

function makeAnthropic(): LLMProvider {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    console.warn('[provider] ANTHROPIC_API_KEY not set, falling back to demo')
    return new DemoProvider()
  }
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { default: Anthropic } = require('@anthropic-ai/sdk') as typeof import('@anthropic-ai/sdk')
  const client = new Anthropic({ apiKey })
  return {
    name: 'anthropic',
    async complete(prompt: string, opts?: { system?: string; json?: boolean }) {
      const resp = await client.messages.create({
        model: process.env.ANTHROPIC_MODEL || 'claude-3-5-sonnet-20241022',
        max_tokens: 2048,
        system: opts?.system ?? undefined,
        messages: [{ role: 'user', content: prompt }]
      })
      return resp.content
        .map((b: any) => (b.type === 'text' ? b.text : ''))
        .join('')
    }
  }
}
