// Pluggable LLM provider.
// - `demo`     : deterministic, template-based responses, NO network / API key needed.
//                This is the default so the whole app runs out-of-the-box (great for local debugging).
// - `openai`   : OpenAI Chat Completions (streaming). Also works with any OpenAI-compatible
//                endpoint when `baseURL` is set (DeepSeek, Moonshot, local vLLM, etc.).
// - `anthropic`: Anthropic Messages API (streaming).
//
// Provider selection + credentials can come from (in priority order):
//   1. an explicit `LLMConfig` passed at runtime (from the Electron settings UI),
//   2. environment variables (AGENT_LLM / OPENAI_API_KEY / ANTHROPIC_API_KEY / ...).

import type { ChatMessage, LLMProvider } from './types.js'

export interface LLMConfig {
  kind?: 'demo' | 'openai' | 'anthropic'
  apiKey?: string
  model?: string
  baseURL?: string
}

// ---------------------------------------------------------------------------

export class DemoProvider implements LLMProvider {
  name = 'demo'

  async complete(prompt: string, _opts?: { system?: string; json?: boolean }): Promise<string> {
    await new Promise((r) => setTimeout(r, 120))
    const lower = prompt.toLowerCase()
    if (_opts?.json) {
      return JSON.stringify({
        note: 'demo-mode structured response',
        echo: prompt.slice(0, 80),
        generated_at: new Date().toISOString()
      })
    }
    const topic = extractTopic(prompt)
    return [
      `## ${topic.title}`,
      '',
      topic.body,
      '',
      '### Key points',
      '- Identify the primary audience and their trigger moments.',
      '- Lead with one clear value proposition, not a feature list.',
      '- Distribute across 3 channels weighted by where the audience spends time.',
      '- Measure with one north-star metric and two guardrail metrics.',
      '',
      '> _Generated by DemoProvider (no API key). Set an API key in ⚙️ Settings for real LLM output._'
    ].join('\n')
  }

  async chat(
    messages: ChatMessage[],
    opts?: { system?: string; onDelta?: (delta: string) => void }
  ): Promise<string> {
    const reply = demoChatReply(messages)
    // Stream word-by-word so the UI feels alive.
    const tokens = reply.match(/\S+\s*|\s+/g) ?? [reply]
    for (const t of tokens) {
      opts?.onDelta?.(t)
      await new Promise((r) => setTimeout(r, 18))
    }
    return reply
  }
}

function demoChatReply(messages: ChatMessage[]): string {
  const lastUser = [...messages].reverse().find((m) => m.role === 'user')?.content?.trim()
  const quote = lastUser ? `你刚才说：“${lastUser}”` : '你还没有发送消息。'
  return [
    '我是你的 **AI 营销团队助手**。当前处于 **Demo 模式**（未接入真实大模型）。',
    '',
    quote + '。',
    '',
    '接入真实模型（OpenAI / Anthropic / 兼容端点）后，我可以：',
    '',
    '- 像现在这样**直接对话**，解答营销、增长、投放、内容策略相关问题；',
    '- 一键调度「营销 Agent」（市场研究 → 内容策略 → 文案 → SEO）生成完整方案；',
    '- 用「数据分析 Agent」读取你的 CSV 并产出可视化图表。',
    '',
    '👉 点击右上角 **⚙️ 设置**，填入 API Key 即可切换到真实模型（支持自定义 baseURL，可接 DeepSeek、Moonshot 等兼容服务）。'
  ].join('\n')
}

function extractTopic(prompt: string): { title: string; body: string } {
  const m = prompt.match(/\[TASK\]\s*(.+?)\n/)
  const label = m ? m[1].trim() : 'Analysis'
  const goalMatch = prompt.match(/Goal:\s*(.+)/)
  const goal = goalMatch ? goalMatch[1].trim() : 'the product / campaign'
  return {
    title: label,
    body: `Below is a structured draft for "${goal}". In demo mode this is a template; ` +
      `with a real LLM provider it would be a tailored, data-grounded deliverable.`
  }
}

// ---------------------------------------------------------------------------

export function getProvider(config?: LLMConfig): LLMProvider {
  const kind = (config?.kind ?? process.env.AGENT_LLM ?? 'demo').toLowerCase()
  if (kind === 'openai') return makeOpenAI(config)
  if (kind === 'anthropic') return makeAnthropic(config)
  return new DemoProvider()
}

function makeOpenAI(config?: LLMConfig): LLMProvider {
  const apiKey = config?.apiKey ?? process.env.OPENAI_API_KEY
  if (!apiKey) {
    console.warn('[provider] no OpenAI API key, falling back to demo')
    return new DemoProvider()
  }
  let OpenAI: typeof import('openai').default
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    OpenAI = require('openai').default
  } catch {
    console.warn('[provider] openai package not installed, falling back to demo')
    return new DemoProvider()
  }
  const client = new OpenAI({
    apiKey,
    baseURL: config?.baseURL ?? process.env.OPENAI_BASE_URL ?? undefined
  })
  const model = config?.model ?? process.env.OPENAI_MODEL ?? 'gpt-4o-mini'
  return {
    name: 'openai',
    async complete(prompt, opts?: { system?: string; json?: boolean }) {
      const resp = await client.chat.completions.create({
        model,
        messages: [
          ...(opts?.system ? [{ role: 'system' as const, content: opts.system }] : []),
          { role: 'user' as const, content: prompt }
        ],
        response_format: opts?.json ? { type: 'json_object' } : undefined
      })
      return resp.choices[0]?.message?.content ?? ''
    },
    async chat(messages, opts?: { system?: string; onDelta?: (d: string) => void }) {
      const stream = await client.chat.completions.create({
        model,
        stream: true,
        messages: [
          ...(opts?.system ? [{ role: 'system' as const, content: opts.system }] : []),
          ...messages.map((m) => ({ role: m.role, content: m.content }))
        ]
      })
      let full = ''
      for await (const chunk of stream) {
        const d = chunk.choices[0]?.delta?.content
        if (d) {
          full += d
          opts?.onDelta?.(d)
        }
      }
      return full
    }
  }
}

function makeAnthropic(config?: LLMConfig): LLMProvider {
  const apiKey = config?.apiKey ?? process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    console.warn('[provider] no Anthropic API key, falling back to demo')
    return new DemoProvider()
  }
  let Anthropic: typeof import('@anthropic-ai/sdk').default
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    Anthropic = require('@anthropic-ai/sdk').default
  } catch {
    console.warn('[provider] @anthropic-ai/sdk not installed, falling back to demo')
    return new DemoProvider()
  }
  const client = new Anthropic({
    apiKey,
    baseURL: config?.baseURL ?? process.env.ANTHROPIC_BASE_URL ?? undefined
  })
  const model = config?.model ?? process.env.ANTHROPIC_MODEL ?? 'claude-3-5-sonnet-20241022'
  return {
    name: 'anthropic',
    async complete(prompt, opts?: { system?: string; json?: boolean }) {
      const resp = await client.messages.create({
        model,
        max_tokens: 2048,
        system: opts?.system ?? undefined,
        messages: [{ role: 'user', content: prompt }]
      })
      return resp.content
        .map((b: any) => (b.type === 'text' ? b.text : ''))
        .join('')
    },
    async chat(messages, opts?: { system?: string; onDelta?: (d: string) => void }) {
      const stream = client.messages.stream({
        model,
        max_tokens: 2048,
        system: opts?.system ?? undefined,
        messages: messages
          .filter((m) => m.role !== 'system')
          .map((m) => ({ role: m.role === 'assistant' ? 'assistant' : 'user', content: m.content }))
      })
      stream.on('text', (delta: string) => opts?.onDelta?.(delta))
      const final = await stream.finalMessage()
      return final.content
        .map((b: any) => (b.type === 'text' ? b.text : ''))
        .join('')
    }
  }
}
